In [ ]:
"""
파이썬: 코드 생산성이 높다
-인터프리터 방식 >때문에 c언어 보다는 프로그램을 효율적으로 짤 수 있다.
 >컴파일러 언어는 동작하기가 더 까다롭다
-동적타입 언어: 변수형 선언 필요 x
 >>정적타입: 변수와 변수형을 선언해줘야 한다
-high-level > 사람이 좀더 프로그래밍 하기 편하다
 >>low-level: 어셈블러/ 기계어 ect...
*파이썬은 느리다?: 반복문ㄴ의 느린 실행속도
 -파이썬은 동적타입 > 타입확인과 함수 디스패치 오버헤드 무조건 발생
 타입확인: 실행시점에서 객체의 타입을 결정
 함수 디스패치: 객체 타입에 맞는 함수를 동적으로 할당
 >>> 반복문의 경우, 각 루프 사이클마다 타입 확인/함수 디스패치의 오버헤드가 커짐
 * 수치연산에 트고하된 라이브러리
   Numpy: 다차원배열을 중심으로 수치계산 함수 제공
    -패키지 설치: pip install numpy
    -패키지 사용: import numpy  as np
 
"""

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
"""
파이썬 리스트:
- 서로 다른 타입의 데이터 저장 가능
-각 데이터 아이템은 객체
numpy 배열:
-서로 다른 타입의 ㄷㅔ이터 저장 가능
-단일 타입일 경우 고정된 타입의 배열로 처리-> 처음 이후엔 타입확인x=> 리스트보다 빠름
"""
#Creating the numpy Array
list = [1, 2, 3, 4]

arr = np.array(list)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [13]:
# dtype attribute
arr.dtype #bit단위로 보여줌

lst = np.array([1, 1.4, "1.1,1.2,2.5"])
lst.dtype

dtype('<U32')

In [16]:
"""
size Comparison of ndarray and list objects
"""
from sys import getsizeof

lst = [1] #64->72 //4bytes 이상 늘어남
print(getsizeof(lst)) # 기본값은 numpy가 더 무거움

arr = np.array([1]) #96->100, int: 4bytes
print(getsizeof(arr))

72
100


In [24]:
"""
Operations with NumPy ans Arrays
"""

prices = [30,25,40,20,20,35,50,35]

#with a list
new_prices = [prices - 5 for prices in prices]
new_prices

# with a ndarray
price_arr = np.array(prices)
price_arr -= 5
print(price_arr)

[25 20 35 15 15 30 45 30]


In [33]:
"""
Ex. 시험 점수 처리
"""

test_1 = np.array([92,94,88,91,87])
test_2 = np.array([79,100,86,93,91])
test_3 = np.array([87,85,72,90,92])

test_3_fixed = test_3 + 2
# print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
# print(total_grade)

final_grade = total_grade / 3
# final_grade
#  2demention
student_scores = np.array([test_1, test_2, test_3_fixed])
jeremy_test_2 = student_scores[1, 3]
manuak_adwoa_test_1 = np.array([student_scores[0,1], student_scores[0,2]])
# print(jeremy_test_2)
# print(manuak_adwoa_test_1)

cody_total = student_scores[:,4] #[:,-1]도 가능
# cody_total

In [41]:
"""
Logical Operations with Arrays
"""
##원소 단위의 논리 연산 가능 > 원소별로 bool값 계산

# masking
a = np.array([10,2,2,4,5,3,9,8,9,7])
mask = a > 5

#Select using losical operations 
selected = a[a > 5] #np.array 변수명[조건]

# combined: AND'&', OR'/'
selected = a[(a > 5) | (a < 3)]
selected = a[(a > 3) & (a < 8)]

array([4, 5, 7])

In [42]:
"""
Exercise: Prridge
"""
porridge = np.array([79,65,50,63,56,90,85,98,79,51])
cold = porridge[porridge < 60]
hot = porridge[porridge > 80]
just_right = porridge[(porridge >= 60) | (porridge <= 80)]

print(cold, hot, just_right)

[50 56 51] [90 85 98] [79 65 50 63 56 90 85 98 79 51]
