In [8]:
import numpy as np

In [11]:
"""
Numpy Array Attributes
"""
# Creating an array
print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [23]:
#random number array

np.random.seed(0)
arr1 = np.random.randint(10, size=(3,4))
print(arr1)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [26]:
#Attributes

np.random.seed(1)
arr = np.random.randint(10, size=(3,4))
arr
print("arr.ndim = ", arr.ndim)
print("arr.shape = ", arr.shape)#
print("arr.size = ", arr.size)#

print("arr.dtype = ", arr.dtype)#
print("arr.itemsize = ", arr.itemsize)
print("arr.nbytes = ", arr.nbytes) #only data 크기 

arr.ndim =  2
arr.shape =  (3, 4)
arr.size =  12
arr.dtype =  int32
arr.itemsize =  4
arr.nbytes =  48


In [28]:
"""
Array Slicing: Accessing Subarrays
"""

arr2 = np.arange(10)

print(arr2)
print(arr2[3:7])
print(arr2[:5])
print(arr2[:5])
print(arr2[::3])
print(arr2[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[0 1 2 3 4]
[0 3 6 9]
[2 4 6]


In [32]:
"""
multi-dimensional Subarrays
"""
np.random.seed(2)
arr = np.random.randint(10,size=(6,8))
# slicing
arr_sub = arr[:2, :2]
print(arr_sub)

# 원본값 변겅
arr_sub[0,0] = 99
print(arr)


[[8 8]
 [5 4]]
[[99  8  6  2  8  7  2  1]
 [ 5  4  4  5  7  3  6  4]
 [ 3  7  6  1  3  5  8  4]
 [ 6  3  9  2  0  4  2  4]
 [ 1  7  8  2  9  8  7  1]
 [ 6  8  5  9  9  9  3  0]]


In [38]:
"""
Subarrays as Views
"""

np.random.seed(3)
arr = np.random.randint(10,size=(6,8))
# copy()
arr_sub1 = arr[:2, :2].copy()
print(arr_sub1)

arr_sub1[0,0] = 100
print(arr)
# print(arr_sub1)

[[8 9]
 [9 9]]
[[8 9 3 8 8 0 5 3]
 [9 9 5 7 6 0 4 7]
 [8 1 6 2 2 1 3 5]
 [8 1 8 7 8 1 0 5]
 [4 1 5 4 7 6 0 0]
 [9 2 4 5 8 8 7 5]]


In [45]:
"""
Reshaping of Array
"""

row_vector = np.arange(1,10)
print(row_vector, '\n')

grid = row_vector.reshape(3,3)
print(grid, '\n')

#차원 추가
arr = np.arange(1,4)
arr_new = arr[np.newaxis, :] #matrix, row_vector
arr_new2 = arr[:, np.newaxis] #matrix, colum_vector

print(arr)
print(arr.shape, '\n')
print(arr_new)
print(arr_new.shape, '\n')
print(arr_new2)
print(arr_new2.shape, '\n')

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3]
(3,) 

[[1 2 3]]
(1, 3) 

[[1]
 [2]
 [3]]
(3, 1) 



In [51]:
"""
Array Concatenation
"""

arr_1 = np.array([[1,2,3],[1,2,3]])
arr_2 = np.array([[4,5,6],[4,5,6]])
arr_3 = np.array([[7,8,9],[7,8,9]])

arr_total = np.concatenate([arr_1, arr_2, arr_3],axis = 0) #2차원 배열일 경우 axis사용해서 종.횡 조절가증
arr_total

# vstack()
arr_total2 = np.vstack([arr_1, arr_2, arr_3])
#차원이 추가됨
arr_total3 = np.hstack([arr_1, arr_2, arr_3])
arr_total

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [52]:
"""
Array Splitting
"""

#split()
arr = np.array([1,2,3,99,99,3,2,1])
arr_1, arr_2, arr_3 = np.split(arr, [3,5])
# 자르는 개수 +1 개의 배열로 나눠진다.
print(arr, '\n')
print(arr_1)
print(arr_2)
print(arr_3)

[1 2 3]
[99 99]
[3 2 1]
