In [35]:
import numpy as np

In [2]:
"""
유니버셜 함수: numpy에서 제공하는 벡터화 연산 함수
(numpy.ufunc)
-다차원배열에 대한 원소 별 연산 수행 // 간결한 문법과 빠른 계산
-벡터화(vectorization): 루프 연산을 인터프리터 계층이 아닌 "컴파일 계층"에서 수행
   >> 배열 연산을 빠르게 처리 가능
 * python loop(for, while)
    ex) for i in range(len(arr))
          arr[i] += 5
 **python: 동적타입언어의 특정상 연산의 속도가 느리다
 * Numpy Universal Functions
 
 *유연한 연산_ 스칼라-벡터,배열배열,다차원배열
 *벡터화 연산이 라이썬 루프보다 대부분 더 효율적임
"""

'\n유니버셜 함수: numpy에서 제공하는 벡터화 연산 함수\n(numpy.ufunc)\n-다차원배열에 대한 원소 별 연산 수행 // 간결한 문법과 빠른 계산\n-벡터화(vectorization): 루프 연산을 인터프리터 계층이 아닌 "컴파일 계층"에서 수행\n   >> 배열 연산을 빠르게 처리 가능\n * python loop(for, while)\n    ex) for i in range(len(arr))\n          arr[i] += 5\n **python: 동적타입언어의 특정상 연산의 속도가 느리다\n * Numpy Universal Functions\n'

In [39]:
"""
Computing reciprocals in loops
"""

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output
values = np.random.randint(1,10,size=5)
print(values)

compute_reciprocals(values)

[6 8 1 2 5]


array([0.16666667, 0.125     , 1.        , 0.5       , 0.2       ])

In [40]:
"""
Comparsion: loop vs ufuncs
"""

big_arr = np.random.randint(1,10,size=1000000)
# 그것의 평균시간 리턴해줌

# looping on a big arr
%timeit compute_reciprocals(big_arr)

2.21 s ± 100 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
# vectorized operations
%timeit 1/ big_arr

6.03 ms ± 540 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1 = np.random.randint(10,size=(5))
arr2 = np.random.randint(10,size=(5))
print(arr1)

arr1 = arr1-2
print(arr1)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10,size=(3,5))
print(arr4)

arr5 = arr4**2
# arr5


[5 8 9 5 0]
[ 3  6  7  3 -2]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]


In [17]:
"""
UFunc
배열의 사칙연산: 파이선 기본 산술 연산자 / UFunc사용
 ex) x = np.arange(4) -> x+3 or np.add(x,3)

"""
# add()
x = np.arange(4)
print("x   =",x)
print("x +3  =",x+3)

##Absolur Value_ np.abs()
#파이썬에서도 빌트인 펑션으로 있지만, 벡터화 연산을 위해 넘파이 이용
x = np.array([-2,-1,0,1,2])
print(np.abs(x))

# 복소수_j붙이면 인식
x = np.array([3+4j,4+3j,2+0j,0+1j])

## linspaxe(start,stop,num) : 선형 간격의 벡터 생성
# 다양한 벡터/행렬생성에 자주 사용

x = np.linspace(0,100,5)

##삼각함수
# np.sin(), np.cos(), np.tan()
# -역삼각함수도 제공함

theta = np.linspace(0,np.pi,3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))



x   = [0 1 2 3]
x +3  = [3 4 5 6]
[2 1 0 1 2]
[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [18]:
"""
etc:
"""
# 지수와 로그np.exp(), np.power, np.log(),np.lon10()
# scipy.special:고급 수치연산을 유니버셜 함수 형태로 제공하는 패키지
#   >> 특수한 분야에서 사용되는 고급수치 연산 유니버셜 함수 제공

'\n\n'

In [21]:
"""
UFuncs: Aggregation
집계하는 함수
"""
## reduce(): 배열을 특정 연산으로 축소
# 각 원소에 대한 연산을 수행한 후 한개의 스칼라 값으로 나오게
x = np.arange(1,5)
print(x)
aggr = np.add.reduce(x)
print(aggr)
aggr = np.multiply.reduce(x)
print(aggr)

print("\n")
# accumulate(): 계산의 중간 결과들을 배열로 저장
x = np.arange(1,15)
print(x)
accum = np.add.accumulate(x)
print(accum)
accum = np.multiply.accumulate(x)
print(accum)

[1 2 3 4]
10
24


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105]
[         1          2          6         24        120        720
       5040      40320     362880    3628800   39916800  479001600
 1932053504 1278945280]


In [27]:
## Summing the values in an Array
#집계함수는 앵간 다 중요
# np.sum()

np.random.seed(2)
arr = np.random.rand(1000000) #rand: create 0-1 real values
print('sum = ',np.sum(arr)) #배열내 원소들을 더해서 결과값 출력

%timeit sum(arr)

sum =  499468.5166853333
183 ms ± 3.44 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [29]:
%timeit np.sum(arr) #파이썬 내장함수보다 빠르다

1.81 ms ± 55.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [31]:
# Other Aggr, functions
#누락값 안전버전 이용하면 누락값 무시하고 연산
print("max = ",np.max(arr))
print("min = ",np.min(arr))
print("mean = ",np.mean(arr))
print("median = ",np.median(arr))
print(np.percentile(arr,50)) #arr이 0-1사이에서 만들어져 있으니까
print(np.any(arr>1))
print(np.all(arr>0))

max =  0.9999976661165695
min =  9.475783189216713e-07
mean =  0.49946851668533326
median =  0.49948650836352526
0.49948650836352526
False
True


In [38]:
"""
Multi dimensional aggregates
다차원 집게: 특정 차원을 기준으로 집계
"""
##axis속성
# 0->1번째 차원인 row방향
# 1->colum방향

np.random.seed(5)

arr = np.random.randint(10,size=(3,4))
print(arr)

print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
[15 28  8]
